services:
  postgres:
    container_name: postgre-db-compose
    image: postgres
    restart: always
    user: ${DB_USER}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    container_name: go-cicd-compose
    image: golang-cicd:v7.0
    restart: always
    env_file:
      - .env
    ports:
        - "8080:8080"
    depends_on:
        - postgres

volumes:
    postgres-data:
